package cn.com.visitbeijing.e.api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "ticketService", targetNamespace = "http://e.visitbeijing.com.cn/api/")
public interface TicketService {

	/**
	 * 
	 * @param in
	 * @return returns java.lang.String
	 */
	@WebMethod(action = "http://e.visitbeijing.com.cn/api/productList/")
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "productList", targetNamespace = "http://e.visitbeijing.com.cn/api/", className = "cn.com.visitbeijing.e.api.ProductList")
	@ResponseWrapper(localName = "productListResponse", targetNamespace = "http://e.visitbeijing.com.cn/api/", className = "cn.com.visitbeijing.e.api.ProductListResponse")
	public String productList(
			@WebParam(name = "in", targetNamespace = "") String in);

	/**
	 * 
	 * @param in
	 * @return returns java.lang.String
	 */
	@WebMethod(action = "http://e.visitbeijing.com.cn/api/resourceList/")
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "resourceList", targetNamespace = "http://e.visitbeijing.com.cn/api/", className = "cn.com.visitbeijing.e.api.ResourceList")
	@ResponseWrapper(localName = "resourceListResponse", targetNamespace = "http://e.visitbeijing.com.cn/api/", className = "cn.com.visitbeijing.e.api.ResourceListResponse")
	public String resourceList(
			@WebParam(name = "in", targetNamespace = "") String in);

	/**
	 * 
	 * @param in
	 * @return returns java.lang.String
	 */
	@WebMethod(action = "http://e.visitbeijing.com.cn/api/productInfo/")
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "productInfo", targetNamespace = "http://e.visitbeijing.com.cn/api/", className = "cn.com.visitbeijing.e.api.ProductInfo")
	@ResponseWrapper(localName = "productInfoResponse", targetNamespace = "http://e.visitbeijing.com.cn/api/", className = "cn.com.visitbeijing.e.api.ProductInfoResponse")
	public String productInfo(
			@WebParam(name = "in", targetNamespace = "") String in);

	/**
	 * 
	 * @param in
	 * @return returns java.lang.String
	 */
	@WebMethod(action = "http://e.visitbeijing.com.cn/api/resourceInfo/")
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "resourceInfo", targetNamespace = "http://e.visitbeijing.com.cn/api/", className = "cn.com.visitbeijing.e.api.ResourceInfo")
	@ResponseWrapper(localName = "resourceInfoResponse", targetNamespace = "http://e.visitbeijing.com.cn/api/", className = "cn.com.visitbeijing.e.api.ResourceInfoResponse")
	public String resourceInfo(
			@WebParam(name = "in", targetNamespace = "") String in);

	/**
	 * 
	 * @param in
	 * @return returns java.lang.String
	 */
	@WebMethod(action = "http://e.visitbeijing.com.cn/api/submitOrder/")
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "submitOrder", targetNamespace = "http://e.visitbeijing.com.cn/api/", className = "cn.com.visitbeijing.e.api.SubmitOrder")
	@ResponseWrapper(localName = "submitOrderResponse", targetNamespace = "http://e.visitbeijing.com.cn/api/", className = "cn.com.visitbeijing.e.api.SubmitOrderResponse")
	public String submitOrder(
			@WebParam(name = "in", targetNamespace = "") String in);

	/**
	 * 
	 * @param in
	 * @return returns java.lang.String
	 */
	@WebMethod(action = "http://e.visitbeijing.com.cn/api/queryProductPrices/")
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "queryProductPrices", targetNamespace = "http://e.visitbeijing.com.cn/api/", className = "cn.com.visitbeijing.e.api.QueryProductPrices")
	@ResponseWrapper(localName = "queryProductPricesResponse", targetNamespace = "http://e.visitbeijing.com.cn/api/", className = "cn.com.visitbeijing.e.api.QueryProductPricesResponse")
	public String queryProductPrices(
			@WebParam(name = "in", targetNamespace = "") String in);

	/**
	 * 
	 * @param in
	 * @return returns java.lang.String
	 */
	@WebMethod(action = "http://e.visitbeijing.com.cn/api/queryOrder/")
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "queryOrder", targetNamespace = "http://e.visitbeijing.com.cn/api/", className = "cn.com.visitbeijing.e.api.QueryOrder")
	@ResponseWrapper(localName = "queryOrderResponse", targetNamespace = "http://e.visitbeijing.com.cn/api/", className = "cn.com.visitbeijing.e.api.QueryOrderResponse")
	public String queryOrder(
			@WebParam(name = "in", targetNamespace = "") String in);

	/**
	 * 
	 * @param in
	 * @return returns java.lang.String
	 */
	@WebMethod(action = "http://e.visitbeijing.com.cn/api/reSendSMS/")
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "reSendSMS", targetNamespace = "http://e.visitbeijing.com.cn/api/", className = "cn.com.visitbeijing.e.api.ReSendSMS")
	@ResponseWrapper(localName = "reSendSMSResponse", targetNamespace = "http://e.visitbeijing.com.cn/api/", className = "cn.com.visitbeijing.e.api.ReSendSMSResponse")
	public String reSendSMS(
			@WebParam(name = "in", targetNamespace = "") String in);

	/**
	 * 
	 * @param in
	 * @return returns java.lang.String
	 */
	@WebMethod(action = "http://e.visitbeijing.com.cn/api/refundTicket/")
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "refundTicket", targetNamespace = "http://e.visitbeijing.com.cn/api/", className = "cn.com.visitbeijing.e.api.RefundTicket")
	@ResponseWrapper(localName = "refundTicketResponse", targetNamespace = "http://e.visitbeijing.com.cn/api/", className = "cn.com.visitbeijing.e.api.RefundTicketResponse")
	public String refundTicket(
			@WebParam(name = "in", targetNamespace = "") String in);

	/**
	 * 
	 * @param in
	 * @return returns java.lang.String
	 */
	@WebMethod(action = "http://e.visitbeijing.com.cn/api/priceInfoList/")
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "priceInfoList", targetNamespace = "http://e.visitbeijing.com.cn/api/", className = "cn.com.visitbeijing.e.api.PriceInfoList")
	@ResponseWrapper(localName = "priceInfoListResponse", targetNamespace = "http://e.visitbeijing.com.cn/api/", className = "cn.com.visitbeijing.e.api.PriceInfoListResponse")
	public String priceInfoList(
			@WebParam(name = "in", targetNamespace = "") String in);

	/**
	 * 
	 * @param in
	 * @return returns java.lang.String
	 */
	@WebMethod(action = "http://e.visitbeijing.com.cn/api/singlePrice/")
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "singlePrice", targetNamespace = "http://e.visitbeijing.com.cn/api/", className = "cn.com.visitbeijing.e.api.SinglePrice")
	@ResponseWrapper(localName = "singlePriceResponse", targetNamespace = "http://e.visitbeijing.com.cn/api/", className = "cn.com.visitbeijing.e.api.SinglePriceResponse")
	public String singlePrice(
			@WebParam(name = "in", targetNamespace = "") String in);

	/**
	 * 
	 * @param in
	 * @return returns java.lang.String
	 */
	@WebMethod(action = "http://e.visitbeijing.com.cn/api/waterCubeValid/")
	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "waterCubeValid", targetNamespace = "http://e.visitbeijing.com.cn/api/", className = "cn.com.visitbeijing.e.api.WaterCubeValid")
	@ResponseWrapper(localName = "waterCubeValidResponse", targetNamespace = "http://e.visitbeijing.com.cn/api/", className = "cn.com.visitbeijing.e.api.WaterCubeValidResponse")
	public String waterCubeValid(
			@WebParam(name = "in", targetNamespace = "") String in);

}
