package cn.com.visitbeijing.e.api;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * ticketService service = new ticketService();
 * TicketService portType = service.getTicketServiceSOAP();
 * portType.productList(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "ticketService", targetNamespace = "http://e.visitbeijing.com.cn/api/", wsdlLocation = "http://e.visitbeijing.com.cn/api/ticketService.php?wsdl")
public class TicketService_Service extends Service {

	private final static URL TICKETSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(cn.com.visitbeijing.e.api.TicketService_Service.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = cn.com.visitbeijing.e.api.TicketService_Service.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://e.visitbeijing.com.cn/api/ticketService.php?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://e.visitbeijing.com.cn/api/ticketService.php?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		TICKETSERVICE_WSDL_LOCATION = url;
	}

	public TicketService_Service(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public TicketService_Service() {
		super(TICKETSERVICE_WSDL_LOCATION, new QName(
				"http://e.visitbeijing.com.cn/api/", "ticketService"));
	}

	/**
	 * 
	 * @return returns TicketService
	 */
	@WebEndpoint(name = "ticketServiceSOAP")
	public TicketService getTicketServiceSOAP() {
		return super.getPort(new QName("http://e.visitbeijing.com.cn/api/",
				"ticketServiceSOAP"), TicketService.class);
	}

}
